name: alma_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - absl-py=2.1.0
  - accelerate=0.34.2
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - cramjam=2.8.3
  - fastparquet=2024.5.0
  - filelock=3.13.1
  - fsspec=2024.2.0
  - idna=3.10
  - Jinja2=3.1.3
  - joblib=1.4.2
  - lxml=5.3.0
  - MarkupSafe=2.1.5
  - mpmath=1.3.0
  - networkx=3.2.1
  - nltk=3.9.1
  - numpy=1.26.3
  - packaging=24.1
  - pandas=2.2.2
  - pillow=10.2.0
  - peft==0.12.0
  - portalocker=2.10.1
  - psutil=6.0.0
  - pyarrow=17.0.0
  - python-dateutil=2.9.0.post0
  - pytz=2024.2
  - pywin32=306
  - PyYAML=6.0.2
  - regex=2024.9.11
  - requests=2.32.3
  - sacrebleu==2.4.3
  - six==1.16.0
  - sympy=1.12
  - tabulate=0.9.0
  - typing_extensions=4.9.0
  - urllib3==2.2.3
  - pip

  - pip:
      - huggingface-hub==0.25.0
      - protobuf==5.28.1
      - rouge_score==0.1.2
      - safetensors==0.4.5
      - sentencepiece==0.2.0
      # - torch==2.4.1
      # - torchaudio==2.4.1
      # - torchvision==0.19.1
      - tqdm==4.66.5
      - tokenizers==0.19.1
      - tzdata==2024.1
      
